name: CI checks

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.feature_set }} features
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        feature_set: [basic, all]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - feature_set: all
            features: test-dev-graph,circuit-params

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --release --workspace --no-default-features --features "${{ matrix.features }}"

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --no-default-features --target ${{ matrix.target }}

  bitrot:
    name: Bitrot check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      # Build benchmarks to prevent bitrot
      - name: Build benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --benches --examples --all-features